# Parameters

# Acceleration due to gravity
# Accepted Values for Planet: Earth, Moon, Mars
planet: Earth

# Mass of the bob
m: 1

# Length of the pendulum
L: 1

# Total amount of time
totalTime: 10

# Step Size for discretization to use in the RK4 integrator
step_size: 0.001

# Inital Angle for the Pendulum
initialAngle: 10