# Parameters

# Acceleration due to gravity
g: 1.6

# Mass of the bob
m: 1

# Length of the pendulum
L: 10

# Total amount of time
totalTime: 10

# Step Size for discretization to use in the RK4 integrator
step_size: 0.001

# Inital Angle for the Pendulum
initialAngle: 20